# Generated by Django 4.0.5 on 2022-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userchoice_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='userchoice_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='userchoice_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
