# Generated by Django 4.0.5 on 2022-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_user_userchoice_email_user_userchoice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
